---

# Installation varialbles
jenkins_pkg_url: "https://pkg.jenkins.io/redhat"
jenkins_version: "2.156-1.1"
jenkins_home: "/var/lib/jenkins"
jenkins_seed_job: "{{ jenkins_home }}/jobs/seed_job"
jenkins_installation_dependecies:
  - java-1.8.0-openjdk

# Configuration variables
jenkins_script_dir: "{{ jenkins_home }}/init.groovy.d"
jenkins_process_user: "jenkins"
jenkins_process_group: "{{ jenkins_process_user }}"
jenkins_default_config_file: "/etc/default/jenkins"
jenkins_default_log_file: "/var/log/jenkins/jenkins.log" 

# User variables
jenkins_admin_username: "admin" 
jenkins_admin_password: "neifn123"

# Plugins
jenkins_plugins: 
  - sonar
  - cloudbees-folder
  - workflow-aggregator
  - greenballs
  - build-timeout 
  - job-dsl
  - ssh-agent
  - timestamper
  - ws-cleanup
  - gradle
  - copyartifact
  - bitbucket
  - subversion
  - ssh-slaves
  - ssh
  - file-operations
  - ant
  - git
  - git-client
  - github
  - github-branch-source
  - gitlab-plugin
  - gradle
  - jquery
