---

- name: Install postgress sql
  yum:
    name: "{{ postgress_components }}"
    state: present
    update_cache: yes
  register: install_postgress
  retries: 6
  delay: 10
  until: install_postgress is success

- name: Run postgress initialization
  shell: "postgresql-setup initdb"
  ignore_errors: yes

- name: Make sure that postgress is stopped
  systemd: 
    name: postgresql 
    state: stopped

- name: Replace postgress config file
  file:
    src: /file/pg_hba.conf
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: "{{ postgres_user }}"
    group: "{{ postgres_user }}"

- name: Make sure that postgress is started
  systemd: 
    name: postgresql 
    state: started
    enabled: yes

- name: Create user for sonarqube
  shell: "createuser {{ sonar_username }}"
  become_user: "{{ postgres_user }}"
  ignore_errors: yes

- name: Create user for sonarqube
  shell: |
    psql -c "ALTER USER {{ sonar_username }} WITH ENCRYPTED password '{{ sonar_password }}';" 
    psql -c "CREATE DATABASE {{ sonar_db }} WITH ENCODING 'UTF8' OWNER {{ sonar_username }} TEMPLATE=template0;"
  become_user: "{{ postgres_user }}"
  ignore_errors: yes