---

- name: Ensure dependencies are installed
  yum:
    name: "{{ jenkins_installation_dependecies }}"
    state: present
    update_cache: yes
  register: install_dependecies
  retries: 6
  delay: 10
  until: install_dependecies is success

- name: Download specific Jenkins version
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}.noarch.rpm"
    dest: "/tmp/jenkins_{{ jenkins_version }}.noarch.rpm"

- name: Install our specific version of Jenkins
  yum:
    name: "/tmp/jenkins_{{ jenkins_version }}.noarch.rpm"
    state: present

