---

- name: Create Android home directory
  file:
    path: "{{ android_home }}"
    owner: "jenkins"
    group: "jenkins"
    state: directory
    mode: 0755

- name: Install prereq
  yum:
    name: "{{ sdk_dependencies }}"
    state: present
    update_cache: yes
  register: install_prereq
  retries: 6
  delay: 10
  until: install_prereq is success

